[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "ohyper.json"


# [target.'cfg(target_os = "none")']
# runner = "bootimage runner"