[package]
name = "ohyper"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
log = "0.4"
bootloader = "0.9"
x86_64 = "0.15.1"
spin = "0.5"
bitflags = "1.3"
